#17 feat: 구매자 회원기능 개발
ssg-240304-java2/wms-justdo pull request #33
Opened 2024-05-17 16:17 UTC by JunRyeol98

구매자 회원 등록 기능 개발 완료했고 ,
구매자 회원 로그인 기능 개발 완료 했습니다.
물품조회의 경우 전체조회까지 개발완료했는데, 데이터가 없어서 샘플데이터가 있을때 테스트 가능할 것 같습니다.

##  작업 내용
- [ ] 구매자 회원 입력 받기
- [ ] 입력받은 회원 데이터 테이블에 저장
- [ ] 구매자 회원으로 로그인처리
- [ ] 구매자 회원 view 생성
- [ ] 물품조회 view 생성
- [ ] 물품조회 처리

## Question
- 카테고리로 상품 검색시 카테고리 전체 출력해주고 번호를 입력받게 해야할까요? 
어떻게 받는게 좋을까요?
- 물품조회의 경우 비회원도 조회가 가능한데 view안에서 상품 선택을 못하는데
회원과 비회원의 물품조회하는 view를 따로 만드는게 좋을까요?

2024-05-17 19:06 UTC, lucinda96 requested changes

2024-05-17 19:06 UTC, lucinda96 commented on src/main/java/com/justdo/fruitfruit/NotificationMapper.java
>  package com.justdo.fruitfruit;
패키지 수정해주세요.
Mapper.java파일들은 com.justdo.fruitfruit.model.dao 안에 있어야합니다.

2024-05-17 19:06 UTC, lucinda96 commented on src/main/java/com/justdo/fruitfruit/controller/UserController.java
> +//    /**
사용하지 않는 코드들은 삭제해주세요

2024-05-17 19:06 UTC, lucinda96 commented on src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
> +        Map<String, String> param = new HashMap<>();
service이후부터는 DTO를 사용하기로 했습니다.
UserDTO를 사용하도록 수정해주세요

2024-05-17 19:06 UTC, lucinda96 commented on src/main/java/com/justdo/fruitfruit/model/service/UserService.java
> +            sqlSession.commit();
resutl값이 있을경우에는 commit
없을경우에는 rollback을 하도록 작성해주세요

2024-05-17 23:35 UTC, lucinda96 commented
메소드별 주석추가 부탁드립니다.

2024-05-18 03:37 UTC, JunRyeol98 commented on src/main/java/com/justdo/fruitfruit/controller/UserController.java
> +//    /**
삭제 완료했습니다.

2024-05-18 03:38 UTC, JunRyeol98 commented on src/main/java/com/justdo/fruitfruit/NotificationMapper.java
>  package com.justdo.fruitfruit;
제파일이 아니고 정훈님 파일입니다. @leejeonghun99

2024-05-18 12:47 UTC, closed without merging