#15 Feat : 판매자 상품 관리 기능 개발 ver2
ssg-240304-java2/wms-justdo pull request #38
Opened 2024-05-18 13:10 UTC by ptecc208

물품 수정, 삭제, 전체 물품 조회 기능 개발 및 테스트

2024-05-18 16:34 UTC, lucinda96 approved these changes
수고하셨습니다.
comment로 남겨 놓은 내용확인해주세요.

2024-05-18 16:34 UTC, lucinda96 commented on src/main/java/com/justdo/fruitfruit/controller/ProductController.java
> +            productDTO.setUserSeq(8); // userSeq 설정
준렬님 로그인기능합쳐지면
다시 테스트 진행해주세요.

2024-05-18 16:44 UTC, lucinda96 requested changes
처음리뷰당시 발견하지못한 카테고리 등록과 관련해 논의가 필요하여
보류상태로 하였습니다.

2024-05-19 01:16 UTC, ptecc208 commented on src/main/resources/sql/seller/ProductMapper.xml
>      <insert id="registerProdCategory" useGeneratedKeys="true" keyColumn="category_seq" keyProperty="categorySeq">
네 알겠습니다

2024-05-19 01:36 UTC, closed without merging